EWLJ-764: Updated tab functionality to handle multiple sets of tabs.
AmericanMedicalAssociation/joe-style-guide pull request #236
Opened 2024-11-13 21:45 UTC by jorge-melo

**Jira Ticket**

- [EWLJ-764: (Mobile) Video Tabs component](https://ama-it.atlassian.net/browse/EWLJ-764)

## Description

Given: Individual has accessed JOE website through mobile device. When the user tries to view a video in the Video Tabs component Then the system should correct the aspect ratio on page load without any interaction from the user.

Current Behavior

In mobile - When first scrolling to the Video Tabs component, the preview image displayed for the first video in the tabs is not sized properly/is cut off (see firest screenshot below). Once you click on another video tab and then click back to the video 1 title tab, it resizes correctly (see second screenshot below).

## To Test

- [ ] Create an "Art of medicine" content type.
- [ ] Make sure to include some videos on "body content" tab under "body component" area.

![Screenshot_13-11-2024_183957_journalofethics lndo site](https://github.com/user-attachments/assets/76f28693-b80c-4e46-bb24-e9eab5c3e96a)

**Go to the page you just created and visualize it as Mobile device.**
![Screenshot 2024-11-13 at 18-43-43 Video tabs heading text test Journal of Ethics American Medical Association](https://github.com/user-attachments/assets/e17c6766-d84b-44dc-8275-dbfb5a4418fc)

**Both video sets should have the same aspect ratio.**

2024-11-14 18:35 UTC, isa-ama commented
@jorge-melo  Issue still there.  Use browserstack to fix the bug.

![Iphonebug1](https://github.com/user-attachments/assets/6bf1be9e-172a-49ee-8d80-9d9b51d00849)

2024-11-15 14:07 UTC, jorge-melo commented
![Screenshot_15-11-2024_105917_live browserstack com](https://github.com/user-attachments/assets/db1f4af3-28ac-43f6-9f75-fe65087cfe99)

2024-11-15 14:23 UTC, isa-ama approved these changes

2024-11-15 14:23 UTC, isa-ama commented
looks good.

2024-11-15 14:27 UTC, isa-ama commented
![desk1](https://github.com/user-attachments/assets/d87f86c2-4c69-4ba1-a19f-e925905636f0)

Make sure the code only applies to **Mobile**

2024-11-15 14:28 UTC, isa-ama commented on styleguide/source/assets/js/vc-video-tabs.js
> +        window.addEventListener('load', () => {
This should apply only for mobile

2024-11-15 14:33 UTC, isa-ama requested changes
The code should apply only for mobile.

2024-11-15 15:08 UTC, isa-ama commented
![roateIphone](https://github.com/user-attachments/assets/c9809a5a-b46f-4833-b507-b426da7c695b)

Issue still there when the phone is rotated.

2024-11-15 18:11 UTC, isa-ama approved these changes

2024-11-15 18:11 UTC, isa-ama commented
Looks good to me.

2024-11-16 00:21 UTC, rgb-ama approved these changes
approved

2024-11-16 00:44 UTC, merged