EWLJ-323: Scroll vertically inside magnified images
AmericanMedicalAssociation/joe-style-guide pull request #29
Opened 2019-04-15 20:16 UTC by shaal

## Ticket(s)

Please do not submit a Pull Request without a relevant JIRA ticket or Github issue! If you are creating a new pattern or feature, create an issue describing the need for this feature in Github **first** and then link to it below.

**Jira Ticket**

- [EWLJ-323: Need figures and images to magnify when magnified](https://issues.ama-assn.org/browse/EWLJ-323)

## Description

Removed CSS rules that limited the image from being displayed full size.

## To Test
- [ ] Switch your JOE SG2 branch to `EWLJ-323-magnify-full-screen-images`
- [ ] Run gulp serve
- [ ] Enable local SG2 in your D8 project
- [ ] In another terminal run `drush @joe.local cr`
- [ ] Go to http://ama-joe.local/article/why-we-need-music-player-every-patient-room/2019-03
- [ ] Click on the magnifying glass in the top-right corner of an image
- [ ] You should see the image displayed on the whole screen, with `X` icon on the top-right corner of the image
- [ ] Confirm that you can scroll down if the image is hight than your screen's resolution
- [ ] Clicking anywhere on the image will close the magnified display and go back to the article page

## Relevant Screenshots/GIFs

Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate behaviors.
![images-magnified-in-full-screen](https://user-images.githubusercontent.com/22901/55031891-0830d080-4fe6-11e9-96e7-3c70c7f3ee4a.jpg)

2019-04-16 21:29 UTC, designerneil commented
The scrolling does not scroll the image 
![Screen Shot 2019-04-16 at 4 29 33 PM](https://user-images.githubusercontent.com/2271747/56245364-d9e26600-6064-11e9-977c-aa80c8cfa8ed.png)

2019-04-17 04:38 UTC, shaal commented
@designerneil When I test the patch again, after clicking on magnifying the image, I do see the scroll-bar and can scroll down. See the screenshot:
![image](https://user-images.githubusercontent.com/22901/56261444-07510300-60a9-11e9-9697-160264c8a39a.png)

2019-04-23 04:45 UTC, shaal commented
@designerneil I think I covered all the edge cases and various browsers where the problem occurred.
With this last commit, this should all be resolved and work as planned.

2019-04-23 17:51 UTC, designerneil commented
@shaal when the magnifier is clicked the image does indeed get larger and I'm able to scroll. But when I close the image the page has scrolled to the top and not maintained my position before I clicked the image. I expect the page scroll position to stay when the magnify is clicked.

2019-04-23 17:53 UTC, designerneil commented
@shaal the close X icon doesn't show up in IE11
![Screen Shot 2019-04-23 at 12 52 54 PM](https://user-images.githubusercontent.com/2271747/56604075-c4ba8980-65c6-11e9-8a42-f7481f88f286.png)

2019-04-23 21:10 UTC, shaal commented
@designerneil I updated the code to be compatible with IE11, and it is now 'remembers' the original scroll position when closing the magnified image.

2019-04-24 21:22 UTC, designerneil requested changes
just change the document.scroll to window

2019-04-24 21:22 UTC, designerneil commented on styleguide/source/assets/js/lightbox.js
> +          $savedScrollPosition = $(document).scrollTop();
```suggestion
          $savedScrollPosition = $(window).scrollTop();
```

2019-04-24 21:22 UTC, designerneil commented on styleguide/source/assets/js/lightbox.js
> +          $savedScrollPosition = $(document).scrollTop();
If it's on document the page still scrolls a little bit when the user scroll within the image

2019-04-24 21:54 UTC, shaal commented
I didn't try the suggestion yet but I'm pretty sure they do the same, and
if it's what I saw yesterday the little 'scroll' that you so see is
probably the effect of header growing to its original height.
When I tested it, the actual scroll position was exactly how it was when
entering the magnified image mode.

On Wed, Apr 24, 2019, 17:22 Neil Gallagher <notifications@github.com> wrote:

> *@designerneil* requested changes on this pull request.
>
> just change the document.scroll to window
> ------------------------------
>
> In styleguide/source/assets/js/lightbox.js
> <https://github.com/AmericanMedicalAssociation/joe-style-guide/pull/29#discussion_r278323074>
> :
>
> > +      // Opens and closes lightbox.
>
> +      $('.joe__inline-image__zoom').click(function() {
>
> +        event.preventDefault();
>
> +        // Unfocus on the dropdown
>
> +        $(this).blur();
>
> +        // add a class to the sibling dropdown
>
> +        $(this).parents('.joe__inline-image').toggleClass('is-zoomed');
>
> +        // While image is zoomed-in, save the scroll position and freeze scrolling.
>
> +        if ($('.layout-container').hasClass('freeze-scrolling')) {
>
> +          $('.layout-container').removeClass('freeze-scrolling');
>
> +          // Restore scroll position before image was magnified.
>
> +          $(document).scrollTop($savedScrollPosition);
>
> +          $savedScrollPosition = 0;
>
> +        } else {
>
> +          // Save scroll position during 'freeze-scrolling'.
>
> +          $savedScrollPosition = $(document).scrollTop();
>
>
> ⬇️ Suggested change
>
> -          $savedScrollPosition = $(document).scrollTop();
>
> +          $savedScrollPosition = $(window).scrollTop();
>
>
> ------------------------------
>
> In styleguide/source/assets/js/lightbox.js
> <https://github.com/AmericanMedicalAssociation/joe-style-guide/pull/29#discussion_r278323228>
> :
>
> > +      // Opens and closes lightbox.
>
> +      $('.joe__inline-image__zoom').click(function() {
>
> +        event.preventDefault();
>
> +        // Unfocus on the dropdown
>
> +        $(this).blur();
>
> +        // add a class to the sibling dropdown
>
> +        $(this).parents('.joe__inline-image').toggleClass('is-zoomed');
>
> +        // While image is zoomed-in, save the scroll position and freeze scrolling.
>
> +        if ($('.layout-container').hasClass('freeze-scrolling')) {
>
> +          $('.layout-container').removeClass('freeze-scrolling');
>
> +          // Restore scroll position before image was magnified.
>
> +          $(document).scrollTop($savedScrollPosition);
>
> +          $savedScrollPosition = 0;
>
> +        } else {
>
> +          // Save scroll position during 'freeze-scrolling'.
>
> +          $savedScrollPosition = $(document).scrollTop();
>
>
> If it's on document the page still scrolls a little bit when the user
> scroll within the image
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AmericanMedicalAssociation/joe-style-guide/pull/29#pullrequestreview-230363049>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAFS5NX4HGPRNQAQ54ILLDPSDFRTANCNFSM4HGDGBNA>
> .
>

2019-04-30 19:49 UTC, designerneil approved these changes

2019-04-30 19:53 UTC, designerneil commented
@shaal I'm closing this PR because it's been replaced by an alternative path the client has chosen. The story for alternative path is https://issues.ama-assn.org/browse/EWLJ-406

2019-05-07 19:41 UTC, merged

2019-05-07 19:41 UTC, designerneil commented
@shaal @cngoody This PR has been merged in and works as described. You are able to scroll within enlarged images.